# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db274de69acec1587792d03847dc58b70fa8283d6711d492dc0c3b3560164743798e8695fc69fc100ce7ff80e64478c05d60dffefaa24ae72c264cef9612435

test:
  secret_key_base: 9971994646b561973edea0de83ab69140a84e9fc7287b3f6c31de5486a9915a8cfa02258cbfc58b03b6a1da153e0048ab0db58cbfd7652b2de701c359a25758a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
